# Generated by Django 2.2 on 2020-03-20 11:12

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', django_extensions.db.fields.json.JSONField(default={})),
                ('opponent', django_extensions.db.fields.json.JSONField(default={})),
                ('player_deck', django_extensions.db.fields.json.JSONField(default={})),
                ('player_played_cards', django_extensions.db.fields.json.JSONField(default=[])),
                ('opponent_played_cards', django_extensions.db.fields.json.JSONField(default=[])),
                ('game_states', django_extensions.db.fields.json.JSONField(default=[])),
                ('instance_mapping', django_extensions.db.fields.json.JSONField(default={})),
            ],
        ),
    ]
